site_name: '{{cookiecutter.product_name}}'
repo_name: '{{cookiecutter.repo_name}}'
site_description: '{{cookiecutter.product_short_description}}'
site_author: '{{cookiecutter.full_name}}'
site_favicon: 'readthedocs/xess.ico'
copyright: '(c) {{cookiecutter.year}} by {{cookiecutter.full_name}}'

pages:
- 'Introduction': 'index.md'
- 'Installation': 'installation.md'
- 'Usage': 'usage.md'
- 'License': 'licenses.md'
- 'History': 'history.md'
- 'Authors': 'authors.md'
- 'Contributing': 'contributing.md'

theme: 'readthedocs'
docs_dir: 'docs/readthedocs'
site_dir: 'site'
